name: bangher
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core app deps
  app_links: ^6.4.1
  auto_size_text: 3.0.0
  blurhash_dart: 1.2.1
  cached_network_image: 3.4.1
  connectivity_plus: ^6.1.5
  csslib: 1.0.2
  csv: 6.0.0
  device_info_plus: 11.5.0
  dropdown_button2: 2.3.9
  easy_debounce: ^2.0.3
  equatable: 2.0.7
  file_picker: ^10.3.2
  flutter_animate: ^4.5.2
  flutter_blurhash: 0.9.1
  flutter_cache_manager: 3.4.1
  flutter_card_swiper: ^7.0.2
  flutter_riverpod: ^2.4.0
  flutter_secure_storage: ^9.2.4
  flutter_spinkit: ^5.2.2
  font_awesome_flutter: ^10.10.0
  from_css_color: 2.0.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  go_router: ^16.2.1
  google_fonts: ^6.2.1
  google_sign_in: ^7.1.1
  hive: 2.2.3
  html: 0.15.6
  http: ^1.5.0
  image: ^4.2.0
  image_picker: ^1.2.0
  intl: 0.20.2
  json_path: ^0.8.0
  lottie: ^3.3.1
  mask_text_input_formatter: 2.9.0
  mime_type: ^1.0.1
  octo_image: 2.1.0
  package_info_plus: ^8.0.0
  page_transition: ^2.2.1
  path: ^1.9.0
  path_provider: ^2.1.5
  percent_indicator: ^4.2.5
  permission_handler: ^12.0.1
  photo_view: 0.15.0
  provider: ^6.1.5+1
  rxdart: ^0.28.0
  shared_preferences: 2.5.3
  sign_in_with_apple: 7.0.1
  smooth_page_indicator: ^1.2.1
  sqflite: ^2.4.2
  supabase_flutter: ^2.10.0
  swipable_stack: ^2.0.0
  synchronized: ^3.4.0
  timeago: 3.7.1
  url_launcher: ^6.3.2
  video_player: 2.10.0
  visibility_detector: ^0.4.0+2
  webview_flutter: ^4.13.0
  crypto: ^3.0.3
  web: ^1.1.0

  # Pro-grade editor/cropper
  extended_image: ^10.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  # Native black splash while Flutter boots (GIF shows after in-app SplashPage)
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/Earth Picture.png

# Native splash config (static black screen before Flutter renders)
flutter_native_splash:
  color: "#000000"
  android_12:
    color: "#000000"
